### ISSUE TITLE
Trying to follow the basic example is failing due to multiple react versions

### ISSUE THREAD

**Issue by barakd** [wix/repluggable#147]
Trying to follow the basic example is failing due to multiple react versions.
![image](https://user-images.githubusercontent.com/7824284/114048194-ffd92480-9892-11eb-8e97-00b497672c65.png)

The reason is that create react app already uses React 17, while repluggable directly depends on react 16.
I suggest changing react to be a peer dependency + dev dependency,  instead of direct dependency.

![image](https://user-images.githubusercontent.com/7824284/114048571-5fcfcb00-9893-11eb-9162-7befa2309b9e.png)

**Comment by itsh01** [comment]
Resolved by https://github.com/wix/repluggable/pull/150
